language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=trunk/ WP_MULTISITE=0
    - WP_VERSION=tags/3.9/ WP_MULTISITE=0
    - WP_VERSION=tags/3.8/ WP_MULTISITE=0
    - WP_VERSION=trunk/ WP_MULTISITE=1
    - WP_VERSION=tags/3.9/ WP_MULTISITE=1
    - WP_VERSION=tags/3.8/ WP_MULTISITE=1

matrix:
    allow_failures:
        - WP_VERSION=tags/3.8/ WP_MULTISITE=0
        - WP_VERSION=tags/3.8/ WP_MULTISITE=1
    fast_finish: true
    

before_script:
    - mkdir -p tmp
    - WP_CORE_DIR=tmp/wordpress/
    - WP_TESTS_DIR=tmp/wordpress-tests/
    - svn co --ignore-externals https://core.svn.wordpress.org/$WP_VERSION tmp/wordpress/
    - svn co --ignore-externals https://unit-tests.svn.wordpress.org/trunk/ tmp/wordpress-tests/
    - cp tmp/wordpress-tests/wp-tests-config-sample.php tmp/wordpress-tests/wp-tests-config.php
    - cp -fr tests/bootstrap-wordpress-unit-test-suite.php tmp/wordpress-tests/includes/bootstrap.php
    - sed -i "s:dirname( __FILE__ ) . '/wordpress/':'$WP_CORE_DIR':" tmp/wordpress-tests/wp-tests-config.php
    - sed -i "s/yourdbnamehere/wordpress_test/" tmp/wordpress-tests/wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" tmp/wordpress-tests/wp-tests-config.php
    - sed -i "s/yourpasswordhere//" tmp/wordpress-tests/wp-tests-config.php
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    - wget https://getcomposer.org/composer.phar
    - php composer.phar install --dev --no-interaction
    - phpenv rehash

script:
    - mkdir -p build/logs
    - phpunit -c phpunit.xml

after_script:
    - php vendor/bin/coveralls --config tests/framework/.coveralls.yml -v --exclude-no-stmt

notifications:
    slack: chriscct7:yd20WubfRqEZM1vlsEhN7E7N
    irc:
        channels:
            - "irc.freenode.net#eddwp"
        template:
            - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"
